# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mariadb:10.8.3
    restart: always
    user: 1000:1000
    environment:
      MARIADB_ROOT_PASSWORD: pa55w0rd
      MARIADB_DATABASE: widgets
    ports:
      - 3306:3306
    volumes:
      - ./db-data/mariadb:/var/lib/mysql
    networks:
      - go-stripe

networks:
  go-stripe: